apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-app
  namespace: default
  labels:
    app: image-processing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing-app
  template:
    metadata:
      labels:
        app: image-processing-app
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
        karpenter.k8s.aws/instance-gpu-name: "t4"
      tolerations:
      - key: nvidia.com/gpu
        effect: NoSchedule
        operator: Exists
      containers:
      - name: image-processing-app
        image: christianhxc/image-processing-app:latest
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8080
          name: metrics
        resources:
          limits:
            nvidia.com/gpu: 1