apiVersion: apps/v1
kind: Deployment
metadata:
  name: montecarlo-pi-graviton
spec:
  selector:
    matchLabels:
      app: montecarlo-pi-graviton
  template:
    metadata:
      labels:
        app: montecarlo-pi-graviton
    spec:      
      nodeSelector:
        demo: compute-optimization
        kubernetes.io/arch: arm64
      containers:
      - name: montecarlo-pi-graviton
        image: christianhxc/montecarlo-pi
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 900m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: montecarlo-pi-graviton
  labels:
    app: montecarlo-pi-graviton
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: montecarlo-pi-graviton
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: montecarlo-pi-graviton
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: montecarlo-pi-graviton
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15