apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        args: ["run", "/scripts/compression-test.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi" 
            cpu: "500m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      restartPolicy: Never
  backoffLimit: 3
---
# Intensive load test job
apiVersion: batch/v1
kind: Job 
metadata:
  name: k6-intensive-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        args: ["run", "/scripts/intensive-test.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      restartPolicy: Never
  backoffLimit: 3
