apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-aggregator-service
  labels:
    app: log-aggregator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-aggregator
  template:
    metadata:
      labels:
        app: log-aggregator
    spec:
      containers:
      - name: log-aggregator
        image: log-aggregator:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: GOMAXPROCS
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: log-aggregator-service
  labels:
    app: log-aggregator
spec:
  selector:
    app: log-aggregator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer