version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/${ECR_USERNAME}
      - REPOSITORY_URI=public.ecr.aws/${IMAGE_REPO_NAME}
  build:
    commands:
      - cd keda/app/
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG-$ARCHITECTURE .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG-$ARCHITECTURE $REPOSITORY_URI:$IMAGE_TAG-$ARCHITECTURE
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG-$ARCHITECTURE
