apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: load-test
spec:
  quiet: "false"
  parallelism: 1
  script:
    configMap:
      name: k6-test-scripts
      file: load-test.js
  runner:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"