apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: perf-test-x86
spec:
  quiet: "false"
  cleanup: post
  parallelism: 1
  script:
    configMap:
      name: k6-test-scripts
      file: perf-test-x86.js
  runner:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"