apiVersion: apps/v1
kind: Deployment
metadata:
  name: montecarlo-pi
spec:
  selector:
    matchLabels:
      app: montecarlo-pi
  template:
    metadata:
      labels:
        app: montecarlo-pi
    spec:
      nodeSelector:
        intent: x86
      tolerations:
      - key: x86
        operator: Exists
      containers:
      - name: montecarlo-pi
        image: public.ecr.aws/chrismld/montecarlo-pi
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 900m
            memory: 512Mi
          limits:
            cpu: 1200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: montecarlo-pi
  labels:
    app: montecarlo-pi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: montecarlo-pi
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: montecarlo-pi
  labels:
    app: montecarlo-pi
    release: prometheus
spec:
  selector:
    matchLabels:
      app: montecarlo-pi
  endpoints:
  - port: http
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: montecarlo-pi-latency
spec:
  scaleTargetRef:
    name: montecarlo-pi
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      metricName: monte_carlo_latency_seconds
      threshold: "0.5"
      query: |
        histogram_quantile(0.95, sum(rate(monte_carlo_latency_seconds_bucket{status="200"}[2m])) by (le))